name: Deploy to cPanel via FTP

on:
  push:
    branches: [Prod, main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SECRET_SERVER }}
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}
          local-dir: .next/
          server-dir: ${{ secrets.SECRET_FTP_DIR }}
